services:
  MySQL:
    image: 'mysql:latest'
    ports:
      - '3305:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - 'MYSQL_DATABASE=nojira'
      - 'MYSQL_PASSWORD=N0J1raD3v'
      - 'MYSQL_ROOT_PASSWORD=N0J1raD3v'
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
volumes:
  persistent: