services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3305:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - 'MYSQL_DATABASE=nojira'
      - 'MYSQL_PASSWORD=N0J1raD3v'
      - 'MYSQL_ROOT_PASSWORD=N0J1raD3v'
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: 'phpmyadmin:latest'
    links:
      - mysql:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
volumes:
  persistent: